#!/bin/sh

# Create Config directory
mkdir -p Config

# Generate Secrets.xcconfig from environment variables
cat > Config/Secrets.xcconfig << EOF
//
//  Secrets.xcconfig
//  MonoTimer
//
// Auto-generated by Xcode Cloud

SUPABASE_URL = ${SUPABASE_URL}
SUPABASE_ANON_KEY = ${SUPABASE_ANON_KEY}
EOF

echo "✅ Created Secrets.xcconfig"
